[aws]
symbol = "  "
format = ""

[buf]
symbol = " "

[c]
symbol = " "

[conda]
symbol = " "

[dart]
symbol = " "

[directory]
read_only = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[git_branch]
format = "on [$symbol$branch(:$remote_branch)](gray) "
symbol = " "

[golang]
symbol = " "

[haskell]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = " "

[meson]
symbol = "喝 "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = " "

[python]
symbol = " "

[rlang]
symbol = "ﳒ "

[ruby]
symbol = " "

[rust]
symbol = ""

[scala]
symbol = " "

[spack]
symbol = "🅢 "

[php]
symbol = "[ ](purple)"

[character]
success_symbol = "[](green)"
error_symbol = "[✗](red) "

[git_status]
format = '([\[ $all_status$ahead_behind\]](white) )'
deleted = "[ ](red)"
conflicted = "[ ](bold blue)"
ahead = "[ ](bold green)"
behind = "[ ](bold red)"
stashed = "[ ](green)"
untracked = "[ ](red)"
modified = "[ ](yellow)"
staged = '[  \($count\)](yellow)'
renamed = "[ ](yellow)"

